### ISSUE TITLE
doesn't work in Puppet4 and earlier

### ISSUE THREAD

**Issue by ch1aki** [tnmt/puppet-tcpdp#3]
As far as I searched, if only source was specified in the package resource, yum provider was selected.
In puppet 4 and earlier,  yum provider doesn't used `source` attribute. 

> [[PUP-3323] yum provider should be able to install from remote URLs - Puppet Tickets](https://tickets.puppetlabs.com/browse/PUP-3323)

Therefore this module fails in installation in my environment(Puppet 4).

So, I forked.
https://github.com/ch1aki/puppet-tcpdp/tree/old-puppet

**Comment by tnmt** [comment]
It's good idea to specify `rpm` provider. would you create PR that fix it?
